services:
  comfyui:
    image: comfyui/comfyui
    container_name: comfyui-engine
    ports:
      - "8188:8188"
    volumes:
      - ../models:/ComfyUI/models
      - ../outputs:/ComfyUI/output
    restart: unless-stopped